services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=config/dev.yaml
    depends_on:
      - database
    restart: unless-stopped

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: filohack
      POSTGRES_PASSWORD: filohack
      POSTGRES_DB: filohack