env: dev # dev, local, prod
postgres:
  host: localhost
  port: 5432
  database: filohack
  username: filohack
  password: filohack
  schema: core
  ssl: false
http_server:
  host: localhost
  port: ":8000"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 60s
  jwt_secret: kdsjisdfunfw88439085dsjfhk;laj039js943234344